- src/views/Buckets.vue
I've fixed this by setting `?limit=-1`, we should ensure that `limit=-1` really means **no limit** on the serverside before merging.
> Fixed export bucket (now doing a full export)

- src/views/Activity.vue
- src/views/Buckets.vue
Re https://github.com/ActivityWatch/activitywatch/issues/84 : add WIP notice in activity view.
Also remove "not implemented" title-text of the JSON export button.
> Wip notices

- Makefile
- package.json
The Activity dropdown doesn't work anymore.
Related issue in bootstrap-vue: https://github.com/bootstrap-vue/bootstrap-vue/issues/747
The specific thing in there affecting us is: "`b-dropdown` popper.js positioning" which is not done as of writing.
> Workaround for bootstrap beta that breaks the dropdown

- src/views/Activity.vue
I think this fixes the following issue: https://github.com/ActivityWatch/activitywatch/issues/117
The reason is that `new Date().toISOString()` returns a datetime normalized to UTC with the 'Z' suffix. When this is later used to construct `moment` objects the timezone information is lost. `moment().format()` preserves the timezone information in the string using the `+HH:MM` suffix.
> Fixed preservation of timezone in handling of datetimes

- src/App.vue
If there is only one host, don’t bother making Activity be a dropdown;
just link directly to the first host.
> Activity button instead of dropdown if one host

- .eslintrc.js
- package-lock.json
- package.json
- src/App.vue
- src/filters.js
- src/main.js
- src/queries.js
- src/resources.js
- src/route.js
- src/style/globalvars.scss
- src/util/color.js
- src/util/event_parsing.js
- src/util/time.js
- src/views/Activity.vue
- src/views/Bucket.vue
- src/views/Buckets.vue
- src/views/Home.vue
- src/views/Log.vue
- src/views/Settings.vue
- src/views/User.vue
- src/visualizations/Summary.vue
- src/visualizations/Sunburst.vue
- src/visualizations/Timeline.vue
- src/visualizations/coloring.js
- src/visualizations/summary.js
- src/visualizations/sunburst.js
- src/visualizations/timeline-simple.js
- src/visualizations/timeline.js
Integrate eslint and prettier with a pre-commit hook. I tried to choose defaults that matched the code style as closely as possible. Second commit applies the eslint fixes (which include prettier) to all the code.
You can run it yourself with 👍 
```
npm run lint
watch --color npm run lint --color
```
Test plan:
- npm run dev
- http://localhost:27180/#/ (make sure server is running in testing mode)
> Integrate eslint and prettier

- src/App.vue
- src/queries.js
- src/views/Activity.vue
Made activity view tabbed.
We need some way to hide stuff such as editors which will not be used by everyone since the page will otherwise be very long, but not sure if this is the perfect solution.
> Made activity view categorized by tabs and added top URL summary

- src/App.vue
- src/views/Activity.vue
Based on https://github.com/ActivityWatch/aw-webui/pull/92
Modifications:
- Simplified menu highlight logic (see https://github.com/ActivityWatch/aw-webui/pull/100/commits/6e992122c3f6b8bf87f34511cbc3b08c172c5a7c)
- Note how the class `active` is already automatically set). 
- Reverted the "show only 5, show 5 less, show 5 more" buttons (I just don't like the look of it)
> Highlight menu items when clicked

- src/queries.js
Data recorded with browsers mentioned in the title will now show up under browser activity.
https://forum.activitywatch.net/t/you-can-now-track-your-web-browsing-with-activitywatch/28/7
> Add support for Firefox Beta/Dev, and Chrome Beta/Unstable

- .github/ISSUE_TEMPLATE/issue-organization-notice.md
Some people sometimes report issues in submodules of the main repo (like [this issue](https://github.com/ActivityWatch/aw-webui/issues/112)). This should be discouraged, so I made an issue template that'll show up when an issue is created to redirect people to the main repo.
> Update issue templates

- src/views/Activity.vue
The date() function returns the date in the URL directly, which doesn't use a timestamp. This means that anytime the app has a date in the URL, it will return results for the wrong timezone.
This changes the dateStart() method to use the ISO formatted date, which will always correctly specify a timezone.
> Fix bug where activity view doesn't use timestamp.

- src/queries.js
Firefox Nightly's window name apparently is Nightly, which is weird. But, since we are only checking for events in the browser bucket, it should be fine to have such a generic name like Nightly?
> Include Firefox Nightly in the Firefox app names

- src/views/Buckets.vue
Features:
-  Fixed so buckets properly exports with metadata
- Add "Import" and "Export all buckets" functionality to web-ui
Bugs:
- ~Neither Firefox nor Chrome seems to care about the download="aw-bucket-export_bucketname.json" and instead gets redirected to a new page with everything in plaintext and not caring about the filename in the "download" tag when pressing CTRL+S and simply gets named "export.json"~ Fixed in aw-server
> Import and export buckets

- src/visualizations/sunburst.js
Sunburst view doesn't work for me and doing this change fixes it.
The fix does not make sense, but it works.
For some reason when importing time in sunburst it does not contain seconds_to_duration, while on other modules where we also import time it does have seconds_to_duration.
> WIP: Sunburst view fix

- src/App.vue
- src/components/StopwatchEntry.vue
- src/route.js
- src/views/Stopwatch.vue
After discussion in #119 and some IRL discussion with @karvla about the UX of the name "Timer"
Also changed the event type to `general.stopwatch` and the bucket name to `aw-stopwatch`
> Renamed Timer to Stopwatch

- src/queries.js
Depends on https://github.com/ActivityWatch/aw-core/pull/76
With this + aw-core change I have tested making buckets with both " and ' in the name and it works properly.
Also works with aw-server-rust.
> Escape bucketname strings

- src/queries.js
https://forum.activitywatch.net/t/web-watcher-doesnt-work-with-brave
Does not work without https://github.com/ActivityWatch/aw-watcher-web/pull/37
> Add brave and opera to browser appnames

- .eslintignore
- package.json
The eslintIgnore that existed in package.json
did not work. This is moved to the .eslintignore
file and should work as intended in this commit.
> Fix: update project to ignore aw-client-js

- src/queries.ts
Vivaldi has currently 2 branches, Vivaldi-stable and Vivaldi-snapshot. Added snapshot to the list. There is also Android version, and we might want to test logging on windows as well (eg. we might need vivaldi.exe added). This is potentially part of bigger issue, having the list of all browsers listed in appnames. Solves: https://github.com/ActivityWatch/activitywatch/issues/314#issuecomment-557589185
> Fix for Vivaldi-snapshot browser logging on Linux

- src/queries.ts
- src/route.js
- src/store/modules/activity_daily.ts
- src/views/Buckets.vue
- src/views/activity/daily/ActivityDaily.vue
- src/views/activity/daily/ActivityDailyBrowser.vue
- src/views/activity/daily/ActivityDailyEditor.vue
- Fixes editor support again so it works with other dates than today again (with vuex)
- Removed support for selecting a specific editor bucket
- Added back "duration" field for browser
Solves https://github.com/ActivityWatch/activitywatch/issues/316
> Add vuex support for editor activity

- src/components/EventEditor.vue
- src/components/StopwatchEntry.vue
- src/views/Stopwatch.vue
There were three bugs:
1. When pressing "stop" we modified the event within StopwatchEntry which
tried to modify the event. Since javascript is reference by value the
actual event in the list was never modified, only the copy. This created
lots of Vue errors every time you pressed "stop"
2. When editing an even it was the same thing, the action was saved in aw-server
but it was not shown in the webui since the parent component was not aware of
the change so you have to reload the webpage.
3. We were using heartbeats instead of an insert when creating events which do
not return anything in aw-server-rust or in aw-server-python with the sqlite
backend. This meant that id was always "null" so instead of stopping the
timer a new identical was created (unless you refreshed the page, then the …
> stopwatch: Fixes broken "stop" and "edit" 

- src/views/QueryExplorer.vue
aw-server-rust does not support single quotes
Also adds a sort_by_duration for a neater query
> QueryExplorer: Replace single quotes with double quotes

- src/store/modules/activity_daily.ts
Demodata that made sense (times adding up) was hard to create before, this fixes that (and adds demodata that actually looks somewhat like real data).
Looks like this:
> Added computation of demo data from single list of events

- src/components/Header.vue
- src/store/modules/activity_daily.ts
- src/store/modules/buckets.js
- src/views/activity/daily/ActivityDailyBrowser.vue
- src/views/activity/daily/ActivityDailyEditor.vue
> See host even if only editor buckets exist

- src/components/ErrorBoundary.vue
This pull request aims to fix my issue #188.
> There's no bucket named 'aw-watcher-window_MYPCHOSTNAME'
While that particular error message does not appear in the latest version of _aw-webui_, it should make it easier for people unfamiliar with a browser's developer tools to spot and report server/API errors.
Furthermore, I added deduplication for error messages. 
PS: My patch worked well on top of https://github.com/ActivityWatch/aw-webui/commit/6379134ac15fa7f13e06bcd4fbdc93ae9fc96b24 – However, I did not verify that error messages are correctly shown with my patch on top of 353634bc585441920650d1660f88208d0dfd0fec.
> Display error message from API requests if available, deduplicate messages

- src/views/activity/Activity.vue
Fixes https://github.com/ActivityWatch/activitywatch/issues/407
> bugfix: Inconsistency when changing period length

- src/components/InputTimeInterval.vue
- src/views/Bucket.vue
- src/views/Buckets.vue
- fix: Fix 'Updated' field in buckets view for aw-server-rust
- The API is slightly different for aw-server-rust
- feat: Add first/last event to Bucket view 
- Only works for aw-server-rust as that's the only one which has the bucket.metadata field
- fix: Set headers on tables where they belong
> Minor improvements to the Buckets and Bucket views

- src/components/EventEditor.vue
- src/components/StopwatchEntry.vue
- src/views/Stopwatch.vue
- src/visualizations/EventList.vue
Also removed it from Stopwatch view so you don't delete events by mistake, you now have to click the "Edit" button first.
Solves feature request in the forum
https://forum.activitywatch.net/t/stopwatch-delete-confirmation-and-pause/659
> feat: Add delete button to EventEditor modal

- src/views/Buckets.vue
Instead of being redirected to an empty page the error is now shown on
the same page and the buckets list reloaded
> feat: Better user experience when importing buckets

- src/components/CategoryEditTree.vue
- src/route.js
- src/views/settings/CategorizationSettings.vue
- src/views/settings/DaystartSettings.vue
- src/views/settings/Settings.vue
- src/views/settings/TimelineDurationSettings.vue
Will make it easier to add more settings later, making each section more isolated from each other and therefore easier to grasp what's relevant and what's not.
> refactor: Split Settings into multiple views

- jest.config.js
- src/App.vue
- src/components/UserSatisfactionPoll.vue
- src/main.js
- vue.config.js
The poll shows up after the user has used ActivityWatch for 30 days. If the user ignores/closes the poll, it will show up after 24 hours again for up to 3 times in total. The user can also choose to not show the poll again. Once the user submits a rating, the poll will not show up again. If the poll receives a rating that is >= 6, it will be a positive rating, otherwise negative. The respective followup alert shows up. 
Closes https://github.com/ActivityWatch/activitywatch/issues/291.
**Poll**
**Positive Feedback Followup**
**Negative Feedback Followup**
- I made this in a b-alert because it worked, @ErikBjare let me know what you feel about this
- I couldn't find the link to sign up for the newsletter
- I think the positive feedback followup might have too many suggested next-steps for …
> feat: poll user satisfaction and calls to action

- src/queries.ts
Fixes regex issue reported in https://forum.activitywatch.net/t/regex-still-doesnt-work/950/6
A real TIL moment for me personally, I had no idea `replace` only replaced the first occurrence... Did a quick `git grep 'replace'` and looks like these were the only ones.
> fix: fixed occurrences of `replace` that should be `replaceAll`

- .eslintrc.json
- src/queries.ts
- src/store/modules/activity.ts
- src/views/activity/Activity.vue
I just banged this out without testing it at all, not sure if it'll work.
**Edit:** Huh, it wasn't too stupid after all. Seems to work...
Also re-adds the 'filter AFK' option.
Replaces #85 
Partially fixes https://github.com/ActivityWatch/activitywatch/issues/261
> feat: progress on audible-as-active

- .github/workflows/nodejs.yml
Progress on true integration tests with fake data using https://github.com/ActivityWatch/aw-fakedata
The idea is to use this for true E2E tests and to make automated & accurate screenshots.
Related to #246
> ci: added starting of aw-server(-rust) in CI for use in integration tests

- src/queries.ts
Add google-chrome-stable to the queries. This is the name of the chrome package when installed from the AUR
> fix: add google-chrome-stable to appnames

- .eslintrc.json
- README.md
- src/util/awclient.js
- vue.config.js
This allows for iterating on the webui with local production data. Added a note to the readme about to set this up.
This made tinkering with the UI code much easier for me.
> feat: set server URL via env vars, and improvements to README

- vue.config.js
Super helpful for in-browser debugging.
> Adding sourcemaps to vue dev builds

- src/index.html
- src/store/modules/activity.ts
While working on https://github.com/ActivityWatch/aw-core/pull/102 I made this change to work around the timeout from the slow query...
> fix: split category_time_by_period query into one for each period to avoid timeout

- src/util/tooltip.js
- src/visualizations/VisTimeline.vue
fix  ActivityWatch/activitywatch#600
added overflow: visible; to VisTimeline.vue to allow tooltip to overflow the container
> fix ActivityWatch/activitywatch#600 timeline cut off

- src/visualizations/VisTimeline.vue
Closes following feature request:  
https://forum.activitywatch.net/t/make-tooltip-hover-in-timeline-view-show-instantly/1560
Before:
After:
> Set delay to 0 for faster timeline tooltips

- src/store/modules/categories.js
- test/unit/store/categories.test.node.js
Fixes https://github.com/ActivityWatch/activitywatch/issues/361#issuecomment-970707045
Deleting a category, then modifying another with an ID subsequent to it, caused  the changes to be applied to unintended classes. This commit fixes it.
> fix: fixed category modification

- src/views/activity/Activity.vue
This makes it much more explicit what range of data you are viewing. A week number isn't very helpful—I have no idea what range of days a number corresponds to. 
Here's what it looks like:
> feat: improve formatting of query range in Activity view

- src/views/activity/Activity.vue
Mitigates activitywatch/activitywatch#706
If there's any sort of migration or data integrity checks run when upgrading AW, maybe it should look for views with a null ID and set the ID to a slugified view name?
> fix: check for missing ID in New View modal

- src/store/modules/activity.ts
- src/util/timeperiod.ts
- src/visualizations/TimelineBarChart.vue
This roughly halved the total loading time of the activity view for me (from ~10s to ~5s).
Should drastically improve performance on sparse days/weeks/months.
> fix(perf): don't query periods without known activity for timeline barchart

- package-lock.json
- src/App.vue
- src/components/Footer.vue
- src/components/Header.vue
- src/components/NewReleaseNotification.vue
- src/components/QueryOptions.vue
- src/components/SelectCategories.vue
- src/components/SelectCategoriesOrPattern.vue
- src/components/UserSatisfactionPoll.vue
- src/main.js
- src/queries.ts
- src/route.js
- src/store/index.js
- src/store/modules/activity.ts
- src/store/modules/buckets.js
- src/store/modules/categories.js
- src/store/modules/server.ts
- src/util/color.ts
- src/views/Report.vue
- src/views/Search.vue
- src/views/Timeline.vue
- src/views/Trends.vue
- src/views/activity/Activity.vue
- src/views/settings/LandingPageSettings.vue
- src/visualizations/VisTimeline.vue
Tried updating vue-awesome, but had to undo due to: https://github.com/Justineo/vue-awesome/issues/207
> feat: started working on Reports view, and some misc cleanup

- src/components/Header.vue
- src/route.js
- src/stores/activity.ts
- src/stores/categories.ts
- src/util/classes.ts
- src/views/Alerts.vue
- src/views/Graph.vue
- src/visualizations/ForceGraph.vue
Generates a graph where:
- node radius is based on the time spent in the category.
- edge force & thickness is based on the number of transitions (not the best metric)
Uses category colors.
- Currently, even the briefest of transitions are counted as just as significant (could reduce this by merging/flooding category-events and removing short category-events)
- Also shouldn't count transitions wider than x seconds apart (or fill such gaps with events that have an "afk" category, since that might also be interesting to see)
- @casaout might have some ideas
- Seems super overkill and hard, but maybe awesome?
> feat: started working on force-directed graph for visualizing category-transitions

- src/components/NewReleaseNotification.vue
- Typo is settingStore data name
- component NewReleaseNotification cannot be permanently disabled or hidden since state data is not in sync with settingStore's state
https://github.com/ActivityWatch/aw-webui/blob/1980a403dfc2a9f54c0700c202d20e17ccf8bba6/src/stores/settings.ts#L43-L49
https://github.com/ActivityWatch/aw-webui/blob/1980a403dfc2a9f54c0700c202d20e17ccf8bba6/src/components/NewReleaseNotification.vue#L42-L44
> fix: fixed NewReleaseNotification couldn't be hidden/disabled

- src/queries.ts
Small edit to appnames list under queries.ts to address issue/request expressed in ActivityWatch/aw-watcher-web#88. I did not add 'Min' browser to the list, as it does not currently have extension support. 
I tested with waterfox on a windows machine and it worked. I am unable to test Orion, as I do not have an OSX machine readily available.
> fix: add browser-queries support for waterfox and orion

- .github/workflows/comment.yml
The expression was treated as a string and always evaluated as true.
> ci: fixed if-statement always evaluating to true in comment.yml

- .gitattributes
- Is recommended by Prettier itself - https://prettier.io/docs/en/options.html#end-of-line
- If this not set, git itself converts the EOLs(by default, to OS specifc EOLs), when code is pulled from repo, so Windows devs will by default will have CRLF files in their working directory
- git will also recognize its own auto-eol-conversions (normalization) as code changes - polluting commit changes
- When comitting code EOLs which is inconflict with .editerconfig or .prettier.yml, which will cause issues in CI as well as local build warns
Ref:
- https://prettier.io/docs/en/options.html#end-of-line
- https://stackoverflow.com/a/2825829/4957939
- https://stackoverflow.com/a/37057962/4957939
> fix: enforce unix-style newlines through .gitattributes

- README.md
There is no generated `static` folder in case of aw-server-rust (unlike aw-server-python), even while packaging rust server, files are directly taken from `aw-server-rust/aw-webui/dist/`.
[aw-server-rust/Makefile](https://github.com/ActivityWatch/aw-server-rust/blob/7c2b31f173194d75634079128a27ed06d83365b1/Makefile#L86)
> docs: better explain how to use pre-releases for dev/testing

- src/views/QueryExplorer.vue
- Load default query from `q` param in url. This allows users to have bookmarks with various queries.
- Expand default query input area. For my taste, it was a bit too small.
> feat: pull default query from query param

- src/components/SelectableVisualization.vue
- src/views/activity/ActivityView.vue
- Shows chronological events on a  timeline for currentDay ± 1day from all (non-empty) buckets.
- For now, does not support greater timeperiod than 'day'
- Automatically updates the data with date-period change
- To add this Visualization, Activity page -> "Edit View" -> "Add Visualization". Click on the Visualization's Settings (⚙) -> "Daily Timeline"
- PR Also fixes large visualizations not being displaced as col-lg-12
> feat: Chronological timeline visualization

- .github/workflows/nodejs.yml
- Makefile
- src/views/QueryExplorer.vue
- test/e2e/screenshot.test.js
- e2e test
- use chrome in local e2e tests as being done in CI
- Narrow down `Selector` to div with `alert` class else larger vue app dialog will be matched
- Actually show the Error content instead of function (https://github.com/ActivityWatch/aw-webui/actions/runs/3325513704/jobs/5498275035#step:12:41)
- Now takes screenshots first and then check and throw errors, so that errors can be visualized in CI itself
- Now takes two screenshot for timeline view since >95% CI errors are on this test and all such errors pertain to timeouts (now even emits the content of `Selector`)
- Fix reactive component missing even after `.count` is `>0` (https://github.com/ActivityWatch/aw-webui/actions/runs/3333810551/jobs/5516122757#step:12:58)
- before throwing errors for debugging
- Added HTTP request …
> fix: ci and e2e test

- src/components/CategoryEditModal.vue
- src/components/CategoryEditTree.vue
- src/components/SelectableVisualization.vue
- src/main.js
- src/stores/activity.ts
- src/stores/categories.ts
- src/util/classes.ts
- src/visualizations/Score.vue
Rebased and salvaged #162
Shouldn't require any changes to backend code.
- ```py
totalScore = 0
for event in events:
totalScore += event.duration * get_score(event.category, allCategories)
return totalScore / (60 * 60)  # from score-seconds to score-hours
```
> feat: add productivity score for categories

- src/queries.ts
that's the name for the package on NIx, 
I fell like generating all variations of browser name should be a better option than what's currently done
> adds Microsoft-edge to list of browser names

- src/queries.ts
I've noticed that data from my Librewolf bucket is not appended to the browser activity.
I've tested changes locally on my NixOS instance and it works for me.
> fix: add librewolf support

- src/queries.ts
Add [Arc](https://arc.net/) browser to macOS
resolve https://github.com/ActivityWatch/aw-watcher-web/issues/111
> fix: support Arc browser on macOS

- src/App.vue
- src/components/SelectableVisualization.vue
- src/main.js
- src/queries.ts
- src/stores/activity.ts
- src/stores/settings.ts
- src/util/awclient.ts
- src/views/settings/Settings.vue
Continuing after https://github.com/ActivityWatch/aw-webui/pull/327
Depends on
- https://github.com/ActivityWatch/aw-server/pull/147
- https://github.com/ActivityWatch/aw-server-rust/pull/428
> feat: server-side settings

- package-lock.json
- package.json
- src/components/SelectableVisualization.vue
- src/stores/activity.ts
Builds on https://github.com/ActivityWatch/aw-client-js/pull/44
Also fixed so that we don't fetch bucket events if vis_timeline is not in the Activity view. (big perf improvement, major decrease in requests!)
For now there will be some verbose logs to make it easy to debug if something is not working, but it can easily be removed in the future.
For now the cache is cleared on page reload.
> feat: added support for query caching in aw-client

- src/queries.ts
No stats about librewolf were shown in Activity->Browser tab. Not so sure about windows portable version, because i can't build this program in windows, but stats were empty too, so i simply copied the process name from task manager.
> fix: better librewolf browser support

- src/views/Timeline.vue
This option enable user to filter  events from different devices or event types on timeline.
> Filtering clients and hosts on timeline

- src/queries.ts
On MacOS, the Vivaldi browser app name is only "Vivaldi". Therefore, the UI cannot filter the browser event for Vivaldi correctly.
> Update app name for Vivaldi browser

- src/views/activity/Activity.vue
Fixes https://github.com/ActivityWatch/activitywatch/issues/1023
Improved date validation in the Activity view by checking if the date is valid using moment.js before proceeding with date manipulations. This prevents errors when the date is cleared or invalid.
> fix: Handle date clearing in Activity view

- src/queries.ts
It looks like this was partially done, so I just cleaned it up. Also added the name of brave browser on macOS.
> refactor: separate brave browser events into their own category

- src/queries.ts
Added the windows arc appname (Arc.exe) to browser_appnames, allowing arc to register as a browser on windows.
> Fix: arc doesn't count as a browser on windows

- src/queries.ts
The browser data showed up in raw data but not in the browser tab, so I added the application name to the list.
The detected name is defined here (StartupWMClass):
https://codeberg.org/librewolf/bsys5/src/branch/master/assets/linux.librewolf.desktop.in
> Add librewolf browser application name for linux

- src/components/UncategorizedNotification.vue
`this.total` is in seconds, not milliseconds
---
- Fixes https://github.com/ActivityWatch/activitywatch/issues/1044
---
<p align=center>
</p>
> fix: showing of `UncategorizedNotification`

- src/queries.ts
Fixes https://github.com/ActivityWatch/activitywatch/issues/968
> Add a browser app name for Microsoft Edge Beta on macOS
