ActivityWatch/aw-webui

- build/webpack.dev.conf.js
- src/App.vue
- src/views/Home.vue
Just needed a small task to get back into the game. Realized how much love the webui really needs code-quality wise.
> Added a connection status indicator

- src/views/Activity.vue
- src/visualizations/summary.js
- src/visualizations/timeline.js
Visualization code is still kind of a mess, but are at least slightly cleaner now and show "Loading..." text while doing REST requests to be more "reactive"
- Added "Loading..." text while doing REST request
- Replaced timeline titleinfo svg with a html table
- Visualization components now work with `create`, `update` and `set_status` methods instead of a single `render`
- Misc refactoring of visualizations
> Visualization status and refactor

- .editorconfig
- package.json
- src/App.vue
- src/util/color.js
- src/util/event_parsing.js
- src/views/Activity.vue
- src/views/Today.vue
- src/visualizations/Sunburst.vue
- src/visualizations/summary.js
- src/visualizations/sunburst.js
I got lazy and didn't write clear commit messages.
Stuff that's changed:
- Added moment-range as a dependency
- Implemented `filterPeriodIntersect` (same behavior as `filter_period_intersect` in aw-core) using moment-range.
- The Activity view now also has a "most common window titles" that uses `filterPeriodIntersect`.
- I moved away from using the view API in the "most common apps" chart, it now uses `filterPeriodIntersect` instead.
- Colors are now predictable (thanks to hashcode and d3.js)
- A bunch of cleanup.
Things left:
> A lot of different stuff

- src/views/Activity.vue
- src/visualizations/timeline.js
- Moved top apps/titles into column layout
- Added ability to toggle filtering of AFK events
- Added ability to toggle showing AFK 'holes' in timeline 
- Gives you a perception of the AFK durations :+1:
> Improved Activity view

- package-lock.json
- package.json
- node-sass 4.5.3 does not support node 9
> Bumped version of node-sass to 4.7.2

- src/App.vue
- src/route.js
- src/views/Bucket.vue
- src/views/QueryExplorer.vue
- src/visualizations/EventList.vue
> Added query explorer

- .babelrc
- package-lock.json
- package.json
- src/views/Activity.vue
- src/views/Home.vue
- Switched to babel-preset-env
- Fixed checkboxes (previously broken)
- Upgraded bootstrap-vue
> Fixes and dependency updates

- src/queries.js
Needed for https://github.com/ActivityWatch/aw-core/pull/50
> Started using lists in queries

- src/visualizations/periodusage.js
New look!
- Changed colors
- Added borders to bars
- Made bars not hit the top (10% top margin)
- Added today indicator
> Made periodusage more beautiful

- README.md
Fixes: https://github.com/ActivityWatch/aw-webui/issues/82
> Add note about CORS configuration in readme

- src/visualizations/periodusage.js
Fixes https://github.com/ActivityWatch/activitywatch/issues/218
> Fixed wrong date on periodusage hover

- src/views/Activity.vue
> Fixed editor activity

- src/views/Activity.vue
- src/views/Buckets.vue
- src/views/QueryExplorer.vue
- src/visualizations/EventList.vue
Just ran:
```sh
find src -type f -print0 | xargs -0 sed -i -e 's/v-on:/@/' -e 's/v-bind:/:/'
```
> Switched to using v-on/v-bind shorthands @/:

- src/App.vue
- src/ErrorBoundary.vue
- src/main.js
- src/views/Activity.vue
- Fixed by `.catch(this.errorHandler)` in the meantime
- Will hopefully be fixed by https://github.com/vuejs/vue/pull/8395
- Someone wrote a hacky mixin that might work in the meantime: https://github.com/vuejs/vue/issues/7653#issuecomment-404817076
> Implemented ErrorBoundary component for cleaner error handling

- src/components/DateRangeInput.vue
- src/components/InputTimeInterval.vue
- src/main.js
- src/util/tooltip.js
- src/views/Bucket.vue
- src/views/Timeline.vue
- src/visualizations/VisTimeline.vue
> Basic input component for time intervals

- .travis.yml
> Added npm cache to travis conf

- src/queries.js
@karvla got this in Xfce, so adding it.
> added Chromium-browser-chromium

- src/views/Activity.vue
I am very embarrassed. I committed, then didn't amend it correctly.
As proof that this commit **does** compile and fix the bug, here's some screenshots:
Before: https://drive.google.com/open?id=1IsDohz3AU4Ie0NzTz3H4aMINiHVIVPF4
After: https://drive.google.com/open?id=1gSY0rh0uADF5iPF5EuWjOCDK3U9F8_rJ
> Fix git copypasta error.

- Makefile
- package-lock.json
- package.json
- src/visualizations/VisTimeline.vue
- Added removal of zero-duration events for performance reasons (removed a little over 1/3 of events during the 30min I worked on this)
- Fixes scrolling on Firefox (and hopefully also Android)
- Removes annoying special build step in Makefile to build vis.js
- Also removed an old and unused Google Charts dependency
> Switched from (unmaintained) vis.js to timeline-plus

- package-lock.json
- src/App.vue
- src/main.js
- src/queries.js
- src/route.js
- src/views/Activity.vue
- src/views/Settings.vue
Was surprisingly easy to implement
> Settings view and startofday setting

- src/App.vue
- src/components/Header.vue
- src/main.js
- src/views/Activity.vue
- src/views/ActivityAndroid.vue
> Redesign header

- src/App.vue
- src/components/Header.vue
- src/route.js
- src/views/ActivityAndroid.vue
Expected to conflict with #139
> Added fixes for Android

- .eslintrc.json
- package-lock.json
- package.json
- src/route.js
- src/store/index.js
- src/store/modules/buckets.js
- src/views/Bucket.vue
- src/views/Buckets.vue
- src/views/Timeline.vue
Makes everything a lot snappier
> Moved buckets into vuex

- README.md
- package-lock.json
The README seemed outdated and the "Getting Started"
section didn't work.
In this commit a "Getting stared" section is added
to make it easier for other developers to setup
the project.
In addition to this some sections are moved/rewritten
to categorize and improve them under "Development" and
"Building".
> Update: improve README instructions

- src/components/InputTimeInterval.vue
1hr isn't enough, 4 hrs is too much, 2hr's is just right (for me). Thanks
> Add 2hr option

- src/queries.ts
Fixes ActivityWatch/activitywatch#324. Tested and works on my computer.
> Fix firefox dev edition browser data not showing up in activity view

- package-lock.json
- package.json
- src/components/EventEditor.vue
- src/components/StopwatchEntry.vue
- src/main.js
- src/util/filters.js
- src/views/Bucket.vue
- src/views/Stopwatch.vue
- src/visualizations/EventList.vue
- Looks a lot better and is basically how Toggl does it
- ~~Not very well tested~~
- ~~Known to not work~~
Adds dependencies needed for vue-datetime.
> Improvements to Stopwatch and EventEditor

- src/components/InputTimeInterval.vue
- src/views/Settings.vue
- src/views/Timeline.vue
Regarding issue #338 https://github.com/ActivityWatch/activitywatch/issues/338
> Added setting for 'show last' duration default value

- src/queries.ts
Fixes https://github.com/ActivityWatch/activitywatch/issues/399
> feat: added support for Edge browser

- src/views/activity/daily/ActivityDaily.vue
> fix: Make week start on Monday instead of Sunday

- src/store/modules/activity_daily.ts
- src/views/activity/daily/ActivityDaily.vue
- src/views/activity/daily/ActivityDailyBrowser.vue
- src/views/activity/daily/ActivityDailyEditor.vue
- src/views/activity/daily/ActivityDailySummary.vue
- src/views/activity/daily/ActivityDailyWindow.vue
I have some ideas about how to solve https://github.com/ActivityWatch/aw-webui/issues/79
This is a requisite to that
> refactor: Made activity_daily vuex more structured and easier to read

- src/views/activity/Activity.vue
- src/visualizations/PeriodUsage.vue
- src/visualizations/periodusage.js
> Subview is now kept when changing date in Activity view

- src/store/modules/buckets.js
> fix: Fix broken getBucketWithEvents

- .github/workflows/nodejs.yml
- src/visualizations/CategoryTree.vue
- src/visualizations/SunburstClock.vue
- src/visualizations/TimelineInspect.vue
- src/visualizations/VisTimeline.vue
- src/visualizations/summary.js
- src/visualizations/sunburst-clock.js
- Add linting to CI
- Fix some linting issues
> Add linting to ci

- src/visualizations/PeriodUsage.vue
> docs: fixed comment in PeriodUsage.vue

- src/visualizations/CategoryTree.vue
> feat: improvements to category tree visualization (collapsible, show percent)

- src/components/SelectableVisualization.vue
- src/store/modules/activity.ts
- src/views/activity/ActivityView.vue
- src/visualizations/SunburstClock.vue
Also fixes the blinking 'data is not available' while loading.
> feat: readded the Sunburst Clock visualization

- src/views/Stopwatch.vue
This fixes ActivityWatch/activitywatch#524.
> fix: fix stopwatch off-by-one error

- src/components/Header.vue
- src/queries.ts
- src/route.js
- src/views/Bucket.vue
- src/views/QueryExplorer.vue
- src/views/Search.vue
- src/visualizations/EventList.vue
> feat: added basic search feature

- src/components/UserSatisfactionPoll.vue
I added full stops to every bullet point, as they all are full sentences, and I also fixed a conditional clause.
> Unify punctuation in satisfaction poll

- src/store/modules/categories.js
- src/views/settings/CategorizationSettings.vue
Todo:
@ErikBjare Do you think that the categorization has a good format right now that we should proceed with, or are there any improvements you have in mind before essentially declaring it a standard format?
> feat: Support import and export of categories

- src/views/settings/CategorizationSettings.vue
Also improved docs in https://github.com/ActivityWatch/docs/pull/61
> docs: added link to categorization docs in settings

- jest.config.js
- src/store/modules/categories.js
- src/store/modules/views.ts
- src/util/classes.ts
- test/unit/store/categories.test.node.js
- test/unit/store/views.test.node.ts
fixes https://github.com/ActivityWatch/activitywatch/issues/580
> fix: fixed bug when editing implicit parent categories, improved testing

- src/views/settings/ColorSettings.vue
- src/views/settings/DaystartSettings.vue
- src/views/settings/LandingPageSettings.vue
- src/views/settings/ReleaseNotificationSettings.vue
- src/views/settings/Settings.vue
- src/views/settings/TimelineDurationSettings.vue
Flexbox magic for better layout, and bootstrap-ified some input elements.
> feat: improved style/layout of settings

- package-lock.json
- package.json
- src/util/color.ts
- src/views/activity/Activity.vue
- src/views/settings/ColorSettings.vue
- src/views/settings/ReleaseNotificationSettings.vue
- src/views/settings/Settings.vue
Not sure if this is the best way to go about it, but it should make the transition less jarring when people update.
> feat: added setting for using color fallback

- src/App.vue
- src/components/Header.vue
- src/style/_container.scss
- src/style/_globals.scss
- src/style/_globalvars.scss
- src/style/style.scss
- src/views/Search.vue
- src/views/activity/Activity.vue
- src/visualizations/PeriodUsage.vue
Made a bunch of style updates that were bothering me. Added comments in the commit messages.
> Style updates

- src/App.vue
- src/components/Header.vue
- src/style/_container.scss
- src/style/_globals.scss
- src/style/_globalvars.scss
- src/style/style.scss
- src/views/Search.vue
- src/views/activity/Activity.vue
- src/visualizations/PeriodUsage.vue
- src/visualizations/SunburstCategories.vue
> Style updates (continued)

- src/components/Header.vue
- src/components/SelectableVisualization.vue
- src/route.js
- src/store/modules/activity.ts
- src/util/datasets.js
- src/util/filters.js
- src/util/timeperiod.ts
- src/views/Trends.vue
- src/views/activity/Activity.vue
- src/visualizations/TimelineBarChart.vue
This is pretty great. 
Started off trying to implement a 'trends' view, but found it a lot easier to start with just adding week/month support to the barchart.
> feat: support weekly/monthly view in barchart visualization

- src/views/activity/Activity.vue
> fix: keep shown currentView when date or periodLength changes

- babel.config.js
- package-lock.json
- package.json
- src/components/EventEditor.vue
- src/components/InputTimeInterval.vue
- src/views/Timeline.vue
- src/visualizations/EventList.vue
- src/visualizations/VisTimeline.vue
- vue.config.js
Requires the following to fetch single events by ID (needed for editing events cut off by query):
> feat: added ability to edit events from timeline view

- package-lock.json
- package.json
- src/components/EventEditor.vue
- src/components/Header.vue
- src/store/modules/activity.ts
- src/views/Bucket.vue
- src/views/Stopwatch.vue
- src/views/activity/Activity.vue
- src/visualizations/EventList.vue
- src/visualizations/VisTimeline.vue
- feat: added 'loading' text to Activity dropdown while buckets being loaded
- build(deps): updated deps
- feat: cancel pending requests when leaving Activity view, better event editing
> Cancel pending requests, and better event editing

- src/views/QueryExplorer.vue
It just feels natural… 😄
I also added a seemingly missing comma. I'm not familiar with _pug_, though, so this may be wrong.
> feat: added "Ctrl+Enter" shortcut for querying in the Query Explorer

- src/components/SelectableEventView.vue
- src/visualizations/VisTimeline.vue
Fixes https://github.com/ActivityWatch/aw-webui/issues/335
> fix: fix timeline in query explorer results

- .eslintrc.json
- src/components/Header.vue
- src/globals.d.ts
- src/route.js
- src/store/modules/buckets.js
- src/store/modules/categories.js
- src/store/modules/settings.ts
- src/views/Alerts.vue
- src/views/activity/Activity.vue
- src/views/settings/DeveloperSettings.vue
See also: https://github.com/ActivityWatch/aw-webui/pull/258
> feat: started working on alerts/goals feature

- src/util/classes.ts
https://element.io/blog/welcome-to-element/
> classes: Rename Riot to Element

- src/util/color.ts
- src/views/Timeline.vue
- src/visualizations/VisTimeline.vue
I'm delivering some optimizations I've done prior to a major rewrite to the timeline view, in the hope that it will ease review for the actual rewrite.
Descriptions are available in each commit.
Some more optimizations have to be done on the rewritten codebase, so this doesn't fix *everything*, but each of them do deliver a significant boost. Also, with the optimizations the server response time starts to become a bit of trouble too: so I'll be proposing some optimizations and API changes in the near future.
Enjoy!
> VisTimeline optimizations

- package-lock.json
- package.json
#341 removed the last use of it.
> Remove vue-property-decorator from dependencies

- .github/workflows/nodejs.yml
- src/queries.ts
- src/stores/activity.ts
- src/stores/buckets.ts
- src/stores/settings.ts
- src/views/Alerts.vue
- src/views/settings/DeveloperSettings.vue
- src/views/settings/LandingPageSettings.vue
- src/visualizations/TimelineBarChart.vue
- test/unit/queries.test.node.js
A few TODOs here and there in the comments.
Goal is to get it to a state where it's at least mergeable, but shoud prob hidden behind a toggle or something until it's more robust.
Also stumbled into a weird import bug when moving around some buckets (bucket was created, but no events were inserted). Buckets were exported from aw-server-rust, and imported into aw-server-python (in case it matters).
> feat: started working on multi-device queries

- src/stores/activity.ts
- src/util/timeperiod.ts
- src/views/activity/Activity.vue
- src/views/activity/ActivityView.vue
- src/visualizations/periodusage.js
Has some minor bugs, but kinda mergeable.
> feat: added last7d and last30d period options to Activity view

- src/views/TimespiralView.vue
- src/visualizations/Timespiral.vue
Learned how to use polyline, neat!
> fix: fixes and improvements to timespiral vis

- .gitignore
- Makefile
- package-lock.json
- package.json
- src/stores/activity.ts
- src/stores/buckets.ts
- src/stores/categories.ts
- src/stores/views.ts
- src/util/classes.ts
- src/util/color.ts
- src/visualizations/sunburst-clock.ts
- test/unit/store/activity.test.node.ts
- test/unit/store/categories.test.node.ts
Vastly improved typing coverage for several store files, among others.
Takes the project coverage from 75.9% to 92.3%.
Note that TS in .vue files is not checked (unsupported by tooling).
> refactor: improved typing coverage (with type-coverage and typescript-coverage-report)

- src/components/CategoryEditModal.vue
- src/components/CategoryEditTree.vue
- src/components/UncategorizedNotification.vue
- src/queries.ts
- src/route.js
- src/stores/activity.ts
- src/stores/categories.ts
- src/views/activity/Activity.vue
- src/views/settings/CategorizationSettings.vue
- src/views/settings/CategoryBuilder.vue
Fetches recent uncategorized events and finds the most common words (by time) which may then be used to create or append category rules with the click of a button.
Also includes a new notification on the Activity view if there's high uncategorized activity (>20%).
> feat: added category-builder to easily make categories from uncategorized time (and a notification when much is uncategorized)

- src/components/CategoryEditModal.vue
- src/stores/categories.ts
- src/util/classes.ts
- src/util/validate.ts
- src/views/settings/ActivePatternSettings.vue
- src/views/settings/CategorizationSettings.vue
- src/views/settings/CategoryBuilder.vue
- Better validation for rule creation and appending
- Escape word when appending to regex in category-builder
- Show dialog when trying to leave with unsaved category changes
> fix: improved categorization settings in several ways (validation, escaping, unsaved changes dialog)

- src/views/QueryExplorer.vue
I ran into this issue and it stumped me for awhile
> fix: print error when __CATEGORIES__ used and no categories set

- src/components/ErrorBoundary.vue
fixes https://github.com/ActivityWatch/aw-webui/issues/392
> fix: ignore CanceledError's in ErrorBoundary messages

- src/visualizations/periodusage.js
fixes https://github.com/ActivityWatch/aw-webui/issues/393
fixes https://github.com/ActivityWatch/activitywatch/issues/843
> fix: fixed periodusage mouseout error (reset color)

- src/components/CategoryEditModal.vue
Ignore case to Case Insensitive
> Wording patch

- src/util/classes.ts
Fixes https://github.com/ActivityWatch/activitywatch/issues/954
> Make the RegEx for GIMP application valid

- src/views/Search.vue
Should convert the rest of the components to ts too.
> fix: fixed Search view returning all events unfiltered, and converted component to typescript

- src/stores/settings.ts
Fixes https://github.com/ActivityWatch/activitywatch/issues/1067
Analysis of the issue in https://github.com/ActivityWatch/activitywatch/issues/1067#issuecomment-2150693674
> fix: fixes issue with migrating category settings to the server
